<?php

/**
 * @file
 * Contains rsvp_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rsvp_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rsvp_core module.
    case 'help.page.rsvp_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Contains customizations related to RSVP Event Project') . '</p>';
      return $output;

    default:
  }
}